name: Deploy Redis to Docker

on:
  push:
    branches: [ main ]
    paths:
      - 'redis.conf'
      - 'Dockerfile'
      - '.github/workflows/deploy-redis.yml'
  workflow_dispatch:  # Enable manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            angeliteai/redis:latest
            angeliteai/redis:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: abandon.angelite.systems
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            docker pull angeliteai/redis:latest
            
            # Check if container exists and stop it
            if [ "$(docker ps -q -f name=redis-instance)" ]; then
              docker stop redis-instance
              docker rm redis-instance
            fi
            
            # Run new container with environment variables and volume mount
            docker run -d \
              --name redis-instance \
              --restart unless-stopped \
              -p 6379:6379 \
              -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
              -v redis-data:/data \
              angeliteai/redis:latest
            
            # Cleanup old images
            docker image prune -af --filter "until=24h"
